salesforce/nimbus

- platforms/apple/Sources/Nimbus/Binder.swift
- platforms/apple/Sources/Nimbus/Callable.swift
- platforms/apple/Sources/Nimbus/Connection.swift
- platforms/apple/Sources/Nimbus/Extensions/DeviceExtension.swift
- platforms/apple/Sources/NimbusTests/BinderTests.swift
> Support throwing methods in `Binder`

- .circleci/config.yml
- .gitignore
- platforms/android/.idea/codeStyles/codeStyleConfig.xml
- platforms/android/build.gradle
- platforms/android/demo-app/build.gradle
- platforms/android/gradle/wrapper/gradle-wrapper.properties
- platforms/android/nimbus-annotations/build.gradle
- platforms/android/nimbus-compiler/build.gradle
- platforms/android/nimbus/build.gradle
First external contribution :-)
- Upgraded `Kotlin` version to the latest (`1.3.50`).
- Added support for `Android Q` (`targetApi = 29`).
- Latest version of `Gradle`.
- Latest versions of some libraries.
> Some version upgrades (and first external contribution)

- docs/site/_includes/docs.njk
- docs/site/docs/ios/writing-a-plugin.md
This is a basic guide for getting started writing a plugin. Any feedback on anything I'm missing or inaccurate is welcome.
> Guide for writing a plugin

- packages/demo-www/public/index.html
- packages/nimbus-bridge/src/index.ts
- platforms/android/nimbus-compiler/src/main/java/com/salesforce/nimbus/NimbusProcessor.kt
- platforms/apple/Sources/Nimbus/Callback.swift
This consolidates the `callCallback` and `callCallback2` functions into a single implementation and makes the necessary changes on both platforms to use the new, unified implementation.
> Callback consolidation

- docs/package.json
- lerna.json
- packages/demo-www/package.json
- packages/nimbus-bridge/package.json
- packages/test-www/package.json
This is the result of the new bump task. Creating this now after a discussion with @threeve that we should bump the version after a release, not immediately before one.
> Bump version to 1.0.0

- docs/site/docs/android/installation.md
- docs/site/docs/android/writing-a-plugin.md
- docs/site/docs/ios/installation.md
- docs/site/docs/ios/writing-a-plugin.md
This includes some minor corrections, instructions for injecting nimbus.js for both platforms, and a basic guide for writing a plugin on Android. Would especially like review for Android related items.
> Documentation Updates

- platforms/apple/Sources/Nimbus/Callback.swift
> Execute callback invocation in a scope to avoid global pollution

- .circleci/config.yml
- platforms/android/nimbus-bridge-webview/src/androidTest/java/com/salesforce/nimbus/bridge/webview/MochaTests.kt
This executes the instrumentation tests of nimbus (mainly the mocha tests) on firebase.
> Firebase testing

- .circleci/config.yml
Looks like an APK location got mixed up in the merge. This fixes that.
> Fix location of test apk

- .circleci/config.yml
This is a cherry-pick from master to add firebase testing to the 1.x release branch.
> 1.0 Firebase Testing

- platforms/apple/Nimbus.xcodeproj/project.pbxproj
- platforms/apple/Sources/Nimbus/Callable.swift
- platforms/apple/Sources/Nimbus/DecodableUtils.swift
- platforms/apple/Sources/Nimbus/JSContextConnection.swift
- platforms/apple/Sources/Nimbus/JSValueCallback.swift
- platforms/apple/Sources/NimbusTests/JSContextConnectionTests.swift
This adds handling for bindable function types to JSContextConnection as well as tests
> JSContextConnection bound function handling

- platforms/apple/Nimbus.xcodeproj/project.pbxproj
- platforms/apple/Sources/Nimbus/Bridge.swift
- platforms/apple/Sources/Nimbus/Connection.swift
- platforms/apple/Sources/Nimbus/JSContextBridge.swift
- platforms/apple/Sources/Nimbus/JSContextConnection.swift
- platforms/apple/Sources/Nimbus/JSEvaluating.swift
- platforms/apple/Sources/Nimbus/JSInvokable.swift
- platforms/apple/Sources/Nimbus/WebViewConnection.swift
- platforms/apple/Sources/NimbusTests/CallJavascriptTests.swift
- platforms/apple/Sources/NimbusTests/InvocationTests.swift
- platforms/apple/Sources/NimbusTests/JSContextConnectionTests.swift
- platforms/apple/Sources/NimbusTests/MochaTests.swift
This adds support for JSContextBridge to call javascript and return the result to the caller.
> Call javascript functions from plugins

- packages/nimbus-bridge/package-lock.json
- platforms/android/gradle/publishing.gradle
Same changes from master but for the release 1.x branch
> Fix bintray upload

- .circleci/config.yml
- docs/site/docs/ios/installation.md
- docs/site/docs/ios/plugin-testing.md
- docs/site/docs/ios/writing-a-plugin.md
- platforms/apple/Nimbus.xcodeproj/project.pbxproj
- platforms/apple/NimbusDesktop/ViewController.swift
- platforms/apple/Sources/Nimbus/Connection.swift
- platforms/apple/Sources/Nimbus/JSContextBridge.swift
- platforms/apple/Sources/Nimbus/JSContextConnection.swift
- platforms/apple/Sources/Nimbus/JSEvaluating.swift
- platforms/apple/Sources/Nimbus/JSValueCallback.swift
- platforms/apple/Sources/Nimbus/JSValueDecoder.swift
- platforms/apple/Sources/Nimbus/JSValueEncoder.swift
- platforms/apple/Sources/Nimbus/Plugin.swift
- platforms/apple/Sources/Nimbus/WebViewBridge.swift
- platforms/apple/Sources/Nimbus/WebViewCallback.swift
- platforms/apple/Sources/Nimbus/WebViewConnection.swift
- platforms/apple/Sources/NimbusMobileApp/ViewController.swift
- platforms/apple/Sources/NimbusTests/CallJavascriptTests.swift
- platforms/apple/Sources/NimbusTests/InvocationTests.swift
- platforms/apple/Sources/NimbusTests/MochaTests.swift
This also changes the name of a couple of classes for consistency.
> Add documentation to new JSCore API

- platforms/android/bridge-v8/src/androidTest/java/com/salesforce/nimbus/bridge/v8/V8PluginTests.kt
- platforms/android/bridge-webview/src/androidTest/java/com/salesforce/nimbus/bridge/webview/MochaTests.kt
- platforms/android/compiler-base/src/main/java/com/salesforce/nimbus/compiler/BinderGenerator.kt
- platforms/android/compiler-v8/src/main/java/com/salesforce/nimbus/bridge/v8/compiler/V8BinderGenerator.kt
- platforms/android/compiler-webview/src/main/java/com/salesforce/nimbus/bridge/webview/compiler/WebViewBinderGenerator.kt
- platforms/android/core/src/main/java/com/salesforce/nimbus/PrimitiveJSONEncodableExtensions.kt
- platforms/android/core/src/test/java/com/salesforce/nimbus/PrimitiveJSONEncodableTests.kt
Now handling Arrays as return types, parameters & callbacks
> Compiler updates to handle Arrays

- platforms/android/nimbusjs/build.gradle
- platforms/android/nimbusjs/src/androidTest/java/com/salesforce/nimbusjs/NimbusJSUtilTests.kt
- platforms/android/nimbusjs/src/main/java/com/salesforce/nimbusjs/NimbusJSUtilities.kt
- remove unused deps
- fix relative path (for consuming as composite build)
- remove duplicate strings in injectedNimbusStream
> Nimbusjs cleanup

- packages/test-www/test/nimbus-core-tests.ts
- packages/test-www/test/shared-tests.js
- platforms/apple/Sources/Nimbus/Binder.swift
- platforms/apple/Sources/Nimbus/CallableBinder.swift
- platforms/apple/Sources/NimbusTests/MochaTests.swift
- platforms/apple/Sources/NimbusTests/SharedTestsJSCore.swift
- platforms/apple/Sources/NimbusTests/SharedTestsPlugin.swift
- platforms/apple/Sources/NimbusTests/SharedTestsWebView.swift
Added the ability for all binding functions with callbacks to have a return value.
This is ONLY for 2.0.  Will be making another PR with the fixes for 1.0.
> iOS functions with callbacks and a non-void return

- platforms/android/compiler-v8/src/main/java/com/salesforce/nimbus/bridge/v8/compiler/V8BinderGenerator.kt
This moves callback assignment outside of the lambda to prevent the parameters being released prior to accessing the callback function. 
Previously a lambda would like like this: 
```
val success: (FetchResponse) -> Unit = { p0 ->
val params = listOf(k2v8!!.toV8(FetchResponse.serializer(), p0))
val callback = parameters.get(1) as V8Function
callback.use { it.call(v8, params.toV8Array(v8)) }
}
```
and `parameters.get(1)` would cause an exception due to the `parameters` already being released. 
Now, the callback variable includes the parameter index and is referenced outside of the lambda like this:
```
val callback1 = parameters.get(1) as V8Function
val success: (FetchResponse) -> Unit = { p0 ->
val params = listOf(k2v8!!.toV8(FetchResponse.serializer(), p0))
callback1.use { it.call(v8, …
```
> Fix for v8 callbacks

- platforms/apple/Nimbus.xcodeproj/project.pbxproj
This reflects the same change made in the release-1.x branch
> Set the NimbusJS deployment target to 11.0

- platforms/apple/Sources/NimbusTests/EventPublisherTests.swift
Add a missing test case to EventPublisherTests
> Add a test for publishing an event twice

- .gitignore
- platforms/android/nimbusjs/.gitignore
- platforms/android/nimbusjs/buildNimbusJS.sh
- platforms/android/nimbusjs/src/androidTest/java/com/salesforce/nimbusjs/NimbusJSUtilTests.kt
- platforms/android/nimbusjs/src/main/java/com/salesforce/nimbusjs/NimbusJSUtilities.kt
* Bundle nimbus.js as an asset rather than raw resource
> Bundle nimbus.js as an asset rather than raw resource (#182)

- .circleci/config.yml
- platforms/apple/Sources/NimbusTests/CallJavascriptTests.swift
This runs tests on both iOS 12 & iOS 13 and adds a missing test case from the EventPublisher
> iOS CI Update

- platforms/apple/Sources/Nimbus/EventPublisher.swift
Some functions in EventPublisher were mistakenly left with an internal protection level.
> Event Publisher public functions

- platforms/android/modules/compiler-v8/src/main/resources/META-INF/gradle/incremental.annotation.processors
- platforms/android/modules/compiler-webview/src/main/resources/META-INF/gradle/incremental.annotation.processors
Incremental annotation support was removed in snapshot PR.  This pr adds it back.
> fix(compiler): add incremental annotation support back 

- lerna.json
- packages/demo-www/package.json
- packages/nimbus-bridge/package.json
- packages/test-www/package.json
- platforms/android/modules/nimbusjs/build.gradle.kts
> Fix an issue where nimbusjs was not executing the copyScript task

- .circleci/config.yml
This will execute the job to publish to cocoa pods trunk after any tagged release or pre-release
> Publish to cocoapods trunk after release and pre-release

- platforms/android/demo-app/src/main/java/com/salesforce/nimbusdemoapp/MainActivity.kt
- platforms/android/modules/bridge-v8/src/main/java/com/salesforce/nimbus/bridge/v8/PrimitiveV8EncodableExtensions.kt
- platforms/android/modules/bridge-v8/src/main/java/com/salesforce/nimbus/bridge/v8/V8Bridge.kt
- platforms/android/modules/bridge-v8/src/main/java/com/salesforce/nimbus/bridge/v8/V8Extensions.kt
- platforms/android/modules/bridge-v8/src/test/java/com/salesforce/nimbus/bridge/v8/V8BridgeTest.kt
- platforms/android/modules/bridge-webview/src/main/java/com/salesforce/nimbus/bridge/webview/WebViewBridge.kt
- platforms/android/modules/bridge-webview/src/main/java/com/salesforce/nimbus/bridge/webview/WebViewExtensions.kt
- platforms/android/modules/bridge-webview/src/test/java/com/salesforce/nimbus/bridge/webview/WebViewBridgeTest.kt
- platforms/android/modules/compiler-v8/src/main/java/com/salesforce/nimbus/bridge/v8/compiler/V8BinderGenerator.kt
- platforms/android/modules/core/src/main/java/com/salesforce/nimbus/Bridge.kt
- platforms/android/modules/core/src/main/java/com/salesforce/nimbus/Runtime.kt
- platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/v8/V8BridgeInvokeTests.kt
- platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/v8/V8PluginTests.kt
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008XdfuIAC/view
Added executor to the V8Bridge
Updated tests.
Pending fix for PrimitiveV8EncodableTests.testBooleanToV8
> W-8040180: Nimbus generated v8 binders need to execute on the v8 executor

- .circleci/config.yml
- platforms/android/gradle/wrapper/gradle-wrapper.properties
Adding gradle settings to help with publishing task
> tweaking gradle build

- platforms/android/build.gradle.kts
- platforms/android/buildSrc/src/main/kotlin/Publishing.kt
- platforms/android/modules/bridge-webview/build.gradle.kts
- platforms/android/modules/compiler-webview/build.gradle.kts
Replacing problematic artifactory plugin with generic maven-publish to fix snapshot publications.
> Replace artifactory plugin with maven-publish

- platforms/android/buildSrc/src/main/kotlin/Versions.kt
- platforms/android/modules/bridge-v8/build.gradle.kts
- platforms/android/modules/bridge-v8/src/androidTest/java/com/salesforce/nimbus/bridge/v8/V8ExtensionsTest.kt
- platforms/android/modules/bridge-v8/src/main/java/com/salesforce/nimbus/bridge/v8/V8Extensions.kt
did two fixes
1. fix the crash issue when bound method return type is Unit
2. fix reference leak issue for promise resolve/reject
> @W-8291379:  primarily fix the crash issue when bound method return type is Unit

- platforms/android/modules/bridge-v8/src/androidTest/java/com/salesforce/nimbus/bridge/v8/V8ExtensionsTest.kt
- platforms/android/modules/bridge-v8/src/main/java/com/salesforce/nimbus/bridge/v8/V8Extensions.kt
Pushed scope handling back to client.
> Revert memory changes

- docs/package.json
- lerna.json
- packages/@nimbus-js/api/package.json
- packages/@nimbus-js/runtime/package.json
- packages/demo-www/package.json
- packages/test-www/package.json
- platforms/android/buildSrc/build.gradle.kts
- platforms/android/buildSrc/src/main/kotlin/Libs.kt
- platforms/android/buildSrc/src/main/kotlin/Versions.kt
- platforms/android/modules/bridge-v8/build.gradle.kts
- platforms/android/modules/compiler-webview/src/main/java/com/salesforce/nimbus/bridge/webview/compiler/WebViewBinderGenerator.kt
- platforms/android/modules/core/src/main/java/com/salesforce/nimbus/Constants.kt
- platforms/android/modules/core/src/main/java/com/salesforce/nimbus/PrimitiveJSONEncodableExtensions.kt
- platforms/android/modules/core/src/main/java/com/salesforce/nimbus/Runtime.kt
- platforms/android/settings.gradle.kts
- platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/plugin/TestPlugin.kt
- platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/v8/V8BridgeInvokeTests.kt
Updated Nimbus to use the following
* Kotlin 1.4.21
* Kotlin.Serialization 1.0.1
* K2v8 1.0.0
> Update Nimbus to use Kotlin 1.4 and Kotlin.Serialization 1.0

- platforms/android/buildSrc/build.gradle.kts
- platforms/android/modules/bridge-v8/src/androidTest/java/com/salesforce/nimbus/bridge/v8/PrimitiveV8EncodableTests.kt
- platforms/android/modules/bridge-v8/src/androidTest/java/com/salesforce/nimbus/bridge/v8/V8ExtensionsTest.kt
- platforms/android/modules/bridge-v8/src/main/java/com/salesforce/nimbus/bridge/v8/V8Bridge.kt
- platforms/android/modules/bridge-v8/src/main/java/com/salesforce/nimbus/bridge/v8/V8Extensions.kt
Did fix in these three areas
1.  V8.resolvePromise had two reference leaks
2. V8.rejectPromise had two reference leaks.
3. Release the reference right away for V8Bridge.kt if really don't need to hold until detach called.
> fix the reference leaks in bridge v8

- platforms/android/buildSrc/build.gradle.kts
- platforms/android/buildSrc/src/main/kotlin/Versions.kt
- platforms/android/modules/compiler-v8/build.gradle.kts
- platforms/android/modules/compiler-v8/src/main/java/com/salesforce/nimbus/bridge/v8/compiler/V8BinderGenerator.kt
- platforms/android/modules/compiler-v8/src/main/java/com/salesforce/nimbus/bridge/v8/compiler/V8BinderGeneratorHelper.kt
- platforms/android/modules/compiler-v8/src/test/kotlin/com/salesforce/nimbus/bridge/v8/compiler/V8BinderGeneratorHelperTest.kt
Primarily to address the memory leak in the generated binder code by the v8 compiler and did some cleanup...
> fix the v8 compiler to avoid some memory leaks for the generated binder code
