salesforce/nimbus

.gitignore
Package.swift

This package description uses the beta version of Swift Package Manager from Xcode 11 beta. The goal is to be ready for consumption as a swift package as soon as Xcode 11 GM ships in the hopes that swiftpm quickly replaces carthage and cocoapods as the defacto iOS/macOS package manager.

Create swift package description for Nimbus

---

demo-www/src/nimbus/app/app.html
demo-www/src/nimbus/app/app.js
platforms/android/demo-app/src/main/java/com/salesforce/nimbusdemoapp/SimpleBridgeExtension.kt
platforms/android/nimbus-compiler/src/main/java/com/salesforce/nimbus/NimbusProcessor.kt
platforms/android/nimbus/build.gradle
platforms/android/nimbus/src/androidTest/java/com/salesforce/nimbus/CallbackTestExtension.kt
platforms/android/nimbus/src/androidTest/java/com/salesforce/nimbus/MochaTests.kt
platforms/android/nimbus/src/main/java/com/salesforce/nimbus/WebViewExtensions.kt
platforms/apple/Nimbus.xcodeproj/project.pbxproj
platforms/apple/Sources/Nimbus/Binder.swift
platforms/apple/Sources/Nimbus/Callback.swift
platforms/apple/Sources/Nimbus/EncodableValue.swift
platforms/apple/Sources/NimbusMobileApp/DemoBridge.swift
platforms/apple/Sources/NimbusTests/BinderTests.swift
platforms/apple/Sources/NimbusTests/MochaTests.swift
test-www/test/callback-encodable-tests.ts
test-www/test/globals.d.ts
test-www/test/index.ts

Non-primitive types can be passed to callback parameters. Following modifications were made:
* In Swift, `bind` methods constraint generic types to `Encodable` so that objects and primitives that can be JSON-ified be passed in.
* In Kotlin, annotation processor was updated to pass `JSONSerializable` object as is.
* Updated mocha tests.
* Updated demo-app.
* Updated binder tests in Swift.
Fixes https://github.com/salesforce/nimbus/issues/51.

Support non-primitive types in callback parameters.

---

package.json

Right now if I `npm install` nimbus (via github url today, but eventually via npm registry) I get all the native platforms and test folders and all that jazz... if I'm installing nimbus via NPM all I want is the dist and src (to see actual source TS files for debugging)... so this change explicitly sets the files to include for NPM packaging.

include src and dist in NPM and ignore everything else

---

platforms/android/nimbus/src/androidTest/java/com/salesforce/nimbus/CallbackTestExtension.kt
platforms/apple/Sources/Nimbus/Callback.swift
platforms/apple/Sources/Nimbus/Connection.swift
platforms/apple/Sources/Nimbus/EncodableValue.swift
platforms/apple/Sources/Nimbus/Generated/Binders.generated.swift
platforms/apple/Sources/Nimbus/Templates/Binders.swifttemplate
platforms/apple/Sources/Nimbus/Templates/Utils.swift
platforms/apple/Sources/NimbusTests/Generated/BinderTests.generated.swift
platforms/apple/Sources/NimbusTests/Templates/BinderTests.swifttemplate

This is a follow-up PR to https://github.com/salesforce/nimbus/pull/87.  It brings #87 to equivalent of close PR #85 using Sourcery code generation. The diff between this PR and #87 should suffice to show the slight improvement there in writing repeated, almost similar bind code in iOS and its respective tests.
I did not mix this code generation improvement using Sourcery with currying improvement as I couldn't put together a solution that both improvements would work together.

Use iOS's Foundation types via sourcery

---

platforms/android/nimbus-compiler/src/main/resources/META-INF/gradle/incremental.annotation.processors

Fixes #113 
Enables incremental annotation processing for the nimbus-compiler.  Now the output from the compiler is:
```
[INFO] com.salesforce.nimbus.NimbusProcessor: total: 121 ms, init: 35 ms, 3 round(s): 85 ms, 1 ms, 0 ms
```
See https://docs.gradle.org/4.7/userguide/java_plugin.html#sec:incremental_annotation_processing for more information

Enable incremental annotation processing

---

docs/site/docs/overview/index.md

Ran across this while reviewing existing doc. Figured it was worth fixing now, while I'd remember it...

Fix link to Getting Started in topic body.

---

docs/site/rfcs/supportRejectInPromiseByTrailingClosure.md

This is a copy of https://github.com/salesforce/nimbus/issues/116 so we can keep a copy of RFC as a part of documentation and trace our decision.

RFC for supporting reject state in promise created with trailing closure.

---

packages/nimbus-bridge/src/index.ts
packages/test-www/test/callback-encodable-tests.ts
platforms/android/nimbus-compiler/src/main/java/com/salesforce/nimbus/NimbusProcessor.kt
platforms/android/nimbus/src/androidTest/java/com/salesforce/nimbus/CallbackTestExtension.kt
platforms/apple/Sources/NimbusTests/MochaTests.swift

Please see https://github.com/salesforce/nimbus/blob/master/docs/site/rfcs/supportRejectInPromiseByTrailingClosure.md for implementation design decisions.
---
Promise created with a trailing closure now supports a rejected state. When a native method throws a string message will be passed as a parameter.  For iOS that string message will be one of the cases in `enum` that implements `Error`.  For Android that string message will be a string that's passed when creating an instance of `Exception` derived class.  The string message can be 'caught' in Javascript like below.
```javascript
doSomething().catch((errorMsg)=>{console.log(errorMsg);});
```

Supporting rejected state in a promise.

---

docs/site/rfcs/nimbusJSDistribution.md

We don't currently have a good option for native consumers to retrieve a built, versioned copy of the nimbus js to inject from the native side. The need to inject nimbus from native seems like a valid use case, both for production and testing, and is something we should support for a 1.0 of Nimbus.
This RFC provides 3 slightly different options for iOS. I have a preference but I don't want to skew any opinions yet.
There is only a single option for Android, because I don't have much experience at all on Android and it seemed straightforward. This would be the area I would like feedback on the most, and any other options that I haven't thought of for Android would be appreciated.

Nimbus javascript Distribution RFC

---

packages/nimbus-bridge/src/index.ts
packages/test-www/test/nimbus-core-tests-setup.ts
packages/test-www/test/nimbus-core-tests.ts

Fixes #122 
To match the behavior on iOS, this change causes existing JS objects to
be preserved.
E.g. if the sample `DeviceExtension` is added to the NimbusBridge, the
following code should work, as it does on iOS
```js
(function() {
const DeviceExtension = window.DeviceExtension || (window.DeviceExtension = {})
DeviceExtension.doSomethingElse = () => {
// Once Nimbus is initialized, window.DeviceExtension
// will have { getDeviceInfo, doSomethingElse }
DeviceExtension.getDeviceInfo().then(info => {
console.log(info)
})
}
})();
```
Prior to this change, the behavior depends on whether the above JS code
executes before or after Nimbus initialization.
With this change, both `getDeviceInfo` and `doSomethingElse` are
always available after initialization, regardless of initialization
order.

Android: preserve and extend JS objects

---

.circleci/config.yml
.gitignore
NimbusJS.podspec
create-nimbus-js.sh
platforms/apple/Nimbus.xcodeproj/project.pbxproj
platforms/apple/Nimbus.xcodeproj/xcshareddata/xcschemes/Nimbus.xcscheme
platforms/apple/Nimbus.xcodeproj/xcshareddata/xcschemes/NimbusJS.xcscheme
platforms/apple/Sources/Nimbus/WebView+NimbusJS.swift
platforms/apple/Sources/NimbusJS/Info.plist
platforms/apple/Sources/NimbusJS/NimbusJS.h
platforms/apple/Sources/NimbusJS/WebView+NimbusJS.swift
platforms/apple/Sources/NimbusJSTests/Info.plist
platforms/apple/Sources/NimbusJSTests/NimbusJSTests.swift
platforms/apple/Sources/NimbusJSTests/testJSSource.js

This creates the NimbusJS podspec which references the zip file published on the 0.0.7 nimbus release artifacts and is composed of the source found in that zip. This also includes a shell script that will assemble the necessary parts expected to be in the zip file. This script will be used primarily by the upcoming CI changes to publish release artifacts.

NimbusJS Podspec

---

.circleci/config.yml

This adds a new job to create a release on GitHub when a new tag is pushed.
This also adds some optimizations to the iOS build and test job.

Automate release creation and artifact publishing

---

.circleci/config.yml

This creates a job, downstream from the android build and test, which only runs when a new tag is pushed (similar to the iOS job). This job runs the Bintray upload gradle task. I've added a user name and API key to Bintray to the circle ci project environment variables. From what I can tell, these are the only variables used by the distribution task not defined in the gradle file itself, but please correct me if I'm mistaken.

Add job for creating and uploading Android distribution binaries

---

packages/nimbus-bridge/src/index.ts
platforms/apple/Nimbus.xcodeproj/project.pbxproj
platforms/apple/Sources/Nimbus/DecodableUtils.swift
platforms/apple/Sources/Nimbus/Generated/Binders.generated.swift
platforms/apple/Sources/Nimbus/Generated/Callables.generated.swift
platforms/apple/Sources/Nimbus/Templates/Binders.swifttemplate
platforms/apple/Sources/Nimbus/Templates/Callables.swifttemplate
platforms/apple/Sources/Nimbus/Templates/Utils.swift
platforms/apple/Sources/NimbusTests/DecodableUtilsTests.swift
platforms/apple/Sources/NimbusTests/Generated/CallableTests.generated.swift
platforms/apple/Sources/NimbusTests/Templates/CallableTests.swifttemplate

Also, change how parameters are passed from javascript. Previously on iOS, parameters were passed as objects. They're now passed as json strings which are attempted to be decoded if the parameter type is Decodable.

Allow parameters to a Callable that conform to Decodable

---

.circleci/config.yml
NimbusBridge.podspec
NimbusJS.podspec
packages/demo-www/package.json
packages/nimbus-bridge/package.json
packages/test-www/package.json
platforms/android/gradle.properties

This does three things
1. Rename Nimbus.podspec to NimbusBridge.podspec to fix a name collision
2. Unify all platform versions and update to 0.99.0 (as discussed offline with @threeve)
3. Add an explicit dependency between NimbusJS and NimbusBridge to ensure consumers aren't using incompatible versions of nimbus.js
We can likely wait to merge this until we are about to release 0.99.0

Rename podspec and bump versions

---

NimbusBridge.podspec
NimbusJS.podspec
packages/demo-www/package.json
packages/nimbus-bridge/package.json
packages/test-www/package.json
platforms/android/gradle.properties

This fixes a mistake in the source url for NimbusJS in 0.99.0

Bump to 0.99.1, fix source url in NimbusJS.podspec

---

.circleci/config.yml
platforms/apple/Nimbus.xcodeproj/project.pbxproj
platforms/apple/Sources/Nimbus/Extensions/DeviceExtension.swift
platforms/apple/Sources/Nimbus/NimbusBridge.swift
platforms/apple/Sources/Nimbus/NimbusExtension.swift
platforms/apple/Sources/Nimbus/Plugin.swift
platforms/apple/Sources/NimbusMobileApp/ViewController.swift
platforms/apple/Sources/NimbusTests/MochaTests.swift

This protocol will replace `NimbusExtension` in v1.0. It takes an
additional parameter which is the bridge the plugin is being bound by.
There is a default implementation that calls through to the old method
for now, but this default implementation and the old protocol will be
removed in the near future.

Add `Plugin` protocol with updated bind api

---

NimbusBridge.podspec
NimbusJS.podspec
lerna.json
package.json
platforms/android/gradle.properties
platforms/android/nimbus-annotations/build.gradle
platforms/android/nimbus-compiler/build.gradle
platforms/android/nimbus/build.gradle
platforms/android/nimbusjs/build.gradle
platforms/apple/Nimbus.xcodeproj/project.pbxproj
sync-apple-versions.sh

This change rallies each platforms version around a single version number, ensuring that version numbers move forward uniformly and with minimal effort.
The single source of version number will be the `lerna.json` file in the project root. We are already using lerna to unify the version of the typescript packages, so this seems like a reasonable resource to make as the source of truth.
When a new version needs to be created, we can run the `bump` task which will move the version number forward.
Android and iOS will then refer to the `lerna.json` file in their respective build scripts and podspecs.
Absent from this PR is any sort of CI check to make sure that version numbers are, in fact, in sync and nothing has broken with the various implementations. Would be interested in feedback on …

Unify version numbers across platforms

---

platforms/android/nimbus-bridge-webview/src/androidTest/java/com/salesforce/nimbus/bridge/webview/MochaTests.kt
platforms/android/nimbus-bridge-webview/src/main/java/com/salesforce/nimbus/bridge/webview/WebViewBridge.kt
platforms/android/nimbus-bridge-webview/src/main/java/com/salesforce/nimbus/bridge/webview/WebViewExtensions.kt
platforms/android/nimbus-bridge-webview/src/test/java/com/salesforce/nimbus/bridge/webview/WebViewBridgeTest.kt
platforms/android/nimbus-compiler-webview/src/main/java/com/salesforce/nimbus/bridge/webview/compiler/WebViewBinderGenerator.kt
platforms/android/nimbus-core/build.gradle
platforms/android/nimbus-core/src/main/AndroidManifest.xml
platforms/android/nimbus-core/src/main/java/com/salesforce/nimbus/Binder.kt
platforms/android/nimbus-core/src/main/java/com/salesforce/nimbus/PrimitiveExtensions.kt
platforms/android/nimbus-core/src/main/java/com/salesforce/nimbus/Runtime.kt
platforms/android/nimbus-core/src/test/java/com/salesforce/nimbus/PrimitiveExtensionsTests.kt

- Moved `PrimitiveExtensions` to `nimbus-core` module
- Made `nimbus-core` module an android library so it can access `JSONObject`
- Updated `WebViewBinderGenerator` to call `Runtime.invoke()` function instead of the `WebView.callJavascript()` extension function
- Removed (Deprecated) `WebView.callJavascript()` extension function

Using Bridge.invoke() and removed WebView.callJavascript() extension

---

platforms/apple/Sources/Nimbus/Binder.swift
platforms/apple/Sources/Nimbus/Callback.swift
platforms/apple/Sources/Nimbus/WebViewConnection.swift
platforms/apple/Sources/NimbusTests/BinderTests.swift

Support for `NSArray` and `NSDictionary` types was added to support a POC but is not actually used. Removing it _significantly_ reduces the complexity of `Binder` by eliminating probably 3/4 of the total overloads. Starting with 2.0 we will explicitly require the use of `Decodable` and `Encodable` only and not support foundation types that use `JSONSerialization`

Remove support for `NSArray` and `NSDictionary` in binders

---

platforms/android/bridge-webview/build.gradle
platforms/android/bridge-webview/src/androidTest/java/com/salesforce/nimbus/bridge/webview/CallbackTestPlugin.kt
platforms/android/bridge-webview/src/androidTest/java/com/salesforce/nimbus/bridge/webview/MochaTests.kt
platforms/android/bridge-webview/src/main/java/com/salesforce/nimbus/bridge/webview/WebViewBridge.kt
platforms/android/bridge-webview/src/main/java/com/salesforce/nimbus/bridge/webview/WebViewExtensions.kt
platforms/android/bridge-webview/src/main/java/com/salesforce/nimbus/bridge/webview/plugins/DeviceInfoPlugin.kt
platforms/android/build.gradle
platforms/android/compiler-base/build.gradle
platforms/android/compiler-base/src/main/java/com/salesforce/nimbus/compiler/BinderGenerator.kt
platforms/android/compiler-base/src/main/java/com/salesforce/nimbus/compiler/CompilerExtensions.kt
platforms/android/compiler-webview/src/main/java/com/salesforce/nimbus/bridge/webview/compiler/WebViewBinderGenerator.kt
platforms/android/core/build.gradle
platforms/android/core/src/main/java/com/salesforce/nimbus/Binder.kt
platforms/android/core/src/main/java/com/salesforce/nimbus/Bridge.kt
platforms/android/core/src/main/java/com/salesforce/nimbus/JSONSerializable.kt
platforms/android/core/src/main/java/com/salesforce/nimbus/JavascriptSerializable.kt
platforms/android/core/src/main/java/com/salesforce/nimbus/Plugin.kt
platforms/android/core/src/main/java/com/salesforce/nimbus/Promise.kt
platforms/android/core/src/main/java/com/salesforce/nimbus/Runtime.kt
platforms/android/core/src/main/java/com/salesforce/nimbus/SerializableExtensions.kt

This adds basic kotlinx-serialization support along side the existing `JSONSerializable` way of serializing to/from a `WebView`. This allows you to just annotate a class with the Kotlin annotation `@Serializable` and in most basic cases the serialization & deserialization will just work. More advanced cases with generic types are currently not supported due to an open [bug](https://github.com/Kotlin/kotlinx.serialization/issues/685) where generic serialization is broken when using `kapt`. More advanced cases can be added later or can currently be accomplished using the existing `JSONSerializable` serialization.
- Added kotlinx-serialization to the project
- Created new `JavascriptSerializable` interface which takes a `SerializedOutputType` type representing the type that the output is …

Basic kotlinx-serialization support

---

packages/nimbus-bridge/package-lock.json
platforms/android/gradle/publishing.gradle

Previously, the bintray uploader was using the version defined in the gradle settings file to upload to bintray as. This changes it to use the central defined version. I've tested this with the dry-run flag.

Use central version when uploading to bintray

---

platforms/android/gradle/publishing.gradle

Missed this in the last PR but is required to correctly set the URL to upload to

Set the project version when doing a bintray upload

---

packages/test-www/test/nimbus-core-tests.ts
platforms/android/bridge-webview/src/androidTest/java/com/salesforce/nimbus/bridge/webview/MochaTests.kt
platforms/apple/Sources/NimbusTests/MochaTests.swift

This adds a number of new tests for exercising plugin API from the javascript side for both iOS and Android. I expect the coverage in the new api testing plugin to increase over time, but this sets up a good base coverage and a pattern to easily expand in the future.

JS API shared Android & iOS Testing

---

platforms/android/bridge-v8/src/main/java/com/salesforce/nimbus/bridge/v8/V8Bridge.kt
platforms/android/bridge-v8/src/main/java/com/salesforce/nimbus/bridge/v8/V8Extensions.kt
platforms/android/bridge-v8/src/test/java/com/salesforce/nimbus/bridge/v8/V8BridgeTest.kt
platforms/android/bridge-webview/src/main/java/com/salesforce/nimbus/bridge/webview/WebViewBridge.kt
platforms/android/bridge-webview/src/main/java/com/salesforce/nimbus/bridge/webview/WebViewExtensions.kt
platforms/android/bridge-webview/src/test/java/com/salesforce/nimbus/bridge/webview/WebViewBridgeTest.kt
platforms/android/compiler-base/src/main/java/com/salesforce/nimbus/compiler/BinderGenerator.kt
platforms/android/compiler-v8/src/main/java/com/salesforce/nimbus/bridge/v8/compiler/V8BinderGenerator.kt
platforms/android/compiler-webview/src/main/java/com/salesforce/nimbus/bridge/webview/compiler/WebViewBinderGenerator.kt
platforms/android/core/src/main/java/com/salesforce/nimbus/Bridge.kt
platforms/android/demo-app/src/main/java/com/salesforce/nimbusdemoapp/MainActivity.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/v8/V8BridgeInvokeTests.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/v8/V8PluginTests.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/webview/WebViewMochaTests.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/webview/WebViewPluginTests.kt

The purpose of this PR is to clean up the API for creating/managing a `Bridge` instance. With the previous API it was possible to call `Bridge.add()` to add `Binders` after the bridge had already been attached which meant that those `Binders` would never get bound to the javascript engine. 
Here is an example of this: 
```
val bridge = WebViewBridge()
bridge.attach(webView)
bridge.add(SomePluginBinder(SomePlugin()))
```
The goal was to not allow this but also make the api a bit easier to read/use.
A `Builder` class was added to each `Bridge` implementation and the `Bridge.add()` and `Bridge.attach()` interface functions were removed and moved to the `Builder`. Now, this is what it looks like to create a bridge:
```
val bridge = WebViewBridge.Builder()
.bind(SomePluginBinder(SomePlugin())) …
```

Added Bridge Builder classes, extension functions to clean up api

---

platforms/apple/Nimbus.xcodeproj/project.pbxproj
platforms/apple/Sources/Nimbus/JSValueEncoder.swift
platforms/apple/Sources/NimbusTests/JSValueEncoderTests.swift
platforms/apple/Sources/NimbusTests/SharedTestsJSCore.swift
platforms/apple/Sources/NimbusTests/SharedTestsPlugin.swift
platforms/apple/Sources/NimbusTests/SharedTestsWebView.swift

This adds the tests added on Android intended to be shared by both platforms to iOS. They are executing in both the webview and JSCore contexts.
One discrepancy is with a test that has a callback with 3 parameters. We don't currently support more than 2 parameters to a callback on iOS, with the intent being there would be a parameter for the result and a parameter for an error. @mattkranzler5 I think we may want to bring Android in line with iOS and find some way to limit Android to only 2 parameters as well. Do you have any thoughts on that?

iOS Shared Testing

---

packages/test-www/test/shared-tests.js
platforms/android/compiler-v8/src/main/java/com/salesforce/nimbus/bridge/v8/compiler/V8BinderGenerator.kt
platforms/android/compiler-webview/src/main/java/com/salesforce/nimbus/bridge/webview/compiler/WebViewBinderGenerator.kt
platforms/android/demo-app/src/main/java/com/salesforce/nimbusdemoapp/MainActivity.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/plugin/TestPlugin.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/v8/V8PluginTests.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/webview/WebViewPluginTests.kt

This PR limits the amount of parameters in a function callback to 2. This brings Android in line with iOS in this respect. The intent is that one parameter is meant for the callback result and the other is the callback error.

Now limiting callbacks to two parameters, fixed bug in demo app

---

platforms/apple/Nimbus.xcodeproj/project.pbxproj
platforms/apple/Sources/Nimbus/Binder.swift
platforms/apple/Sources/Nimbus/CallableBinder.swift
platforms/apple/Sources/Nimbus/JSValueCallback.swift
platforms/apple/Sources/NimbusMobileApp/ConsolePlugin.swift
platforms/apple/Sources/NimbusMobileApp/JSCoreDemo.js
platforms/apple/Sources/NimbusMobileApp/ViewController.swift
platforms/apple/Sources/NimbusTests/BinderTests.swift

This adds a simple demo of calling the device info plugin from jscore, then logging the result to another console plugin added in the demo app.

Add JSCore Demo Content to DemoApp

---

lerna.json
packages/demo-www/package.json
packages/nimbus-bridge/package.json
packages/test-www/package.json
packages/test-www/test/callback-encodable-tests.ts
platforms/apple/Sources/Nimbus/Generated/Binders.generated.swift
platforms/apple/Sources/Nimbus/Templates/Binders.swifttemplate
platforms/apple/Sources/NimbusTests/Generated/BinderTests.generated.swift
platforms/apple/Sources/NimbusTests/MochaTests.swift
platforms/apple/Sources/NimbusTests/Templates/BinderTests.swifttemplate

Gives the ability to bind a function which uses call backs to have a return type that is not void.

iOS binders with callbacks to support non-void returns

---

packages/test-www/test/shared-tests.js
platforms/android/compiler-base/src/main/java/com/salesforce/nimbus/compiler/BinderGenerator.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/plugin/TestPlugin.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/v8/V8PluginTests.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/webview/WebViewPluginTests.kt

This PR adds a custom date serializer and some shared tests to the `shared-tests` module to verify custom serializers work properly with JSON & K2V8 serializers.

Fix for custom serializer, added date serialization to shared tests 

---

platforms/apple/Nimbus.xcodeproj/project.pbxproj

This fixes the Xcode project, used by Carthage consumers, to make the nimbus and nimbus js deployment targets match at 11.0

Make the nimbus js deployment target match the nimbus deployment target

---

packages/test-www/test/callback-encodable-tests.ts
platforms/android/nimbus/src/androidTest/java/com/salesforce/nimbus/CallbackTestPlugin.kt

Extend the android callback test plugin to support nimbus tests for bound method return value as promise

add auto test for android bound method return

---

platforms/android/annotations/src/main/java/com/salesforce/nimbus/PluginOptions.kt
platforms/android/compiler-base/src/main/java/com/salesforce/nimbus/compiler/BinderGenerator.kt
platforms/android/compiler-v8/src/main/java/com/salesforce/nimbus/bridge/v8/compiler/V8BinderGenerator.kt
platforms/android/compiler-webview/src/main/java/com/salesforce/nimbus/bridge/webview/compiler/WebViewBinderGenerator.kt

Added a couple flags to `PluginOptions` to support disabling binder generation for each type. Here is an example if you would like to disable generating a V8Binder for a plugin:
```
@PluginOptions(name="MyPlugin", supportsV8=false)
```
Since V8 binders require Kotlin Serializable support this can be useful if a project pulls in a dependency that transitively uses `bridge-v8` but the project doesn't support Kotlin Serializable and still uses `JSONEncodable` to encode/decode to/from a webview. In this case they can disable V8 binders for their plugins so their won't be any compiler errors.

Allow disabling binder generation

---

packages/test-www/test/nimbus-core-tests.ts
packages/test-www/test/shared-tests.js
platforms/android/compiler-v8/src/main/java/com/salesforce/nimbus/bridge/v8/compiler/V8BinderGenerator.kt
platforms/android/compiler-webview/src/main/java/com/salesforce/nimbus/bridge/webview/compiler/WebViewBinderGenerator.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/plugin/TestPlugin.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/v8/V8PluginTests.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/webview/WebViewMochaTests.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/webview/WebViewPluginTests.kt

This PR makes the change that was already made in iOS to support a return value from bound methods that take a callback as a parameter. This was a compiler error previously.

Now supporting non-void return values for functions that take a callback

---

platforms/apple/Sources/Nimbus/Binder.swift
platforms/apple/Sources/Nimbus/CallableBinder.swift
platforms/apple/Sources/NimbusTests/BinderTests.swift

These overloaded `bind` methods are unique in that they take a second callback as one of the arguments.
Android already supports the second callback via its @BoundMethod annotation.

Added overloads for the bind method.

---

packages/nimbus-bridge/src/index.ts
packages/test-www/test/callback-encodable-tests.ts
platforms/android/nimbus/src/androidTest/java/com/salesforce/nimbus/CallbackTestPlugin.kt
platforms/apple/Sources/Nimbus/Connection.swift
platforms/apple/Sources/Nimbus/EncodableValue.swift
platforms/apple/Sources/NimbusTests/MochaTests.swift

Rejected promises were sending the `undefined` data of a failed resolve type.
Now sending the `error` instead.

Promise rejection fix

---

platforms/apple/Sources/Nimbus/WebViewBridge.swift
platforms/apple/Sources/Nimbus/WebViewConnection.swift
platforms/apple/Sources/NimbusTests/MochaTests.swift
platforms/apple/Sources/NimbusTests/SharedTestsWebView.swift

This changes WebViewConnection to only generate a single WKUserScript per plugin. This also changes SharedTestsWebView to use a single test function per test case, rather than batching all test cases into a single function.

WKUserScript Optimization

---

packages/nimbus-bridge/src/index.ts
packages/test-www/test/callback-encodable-tests.ts
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/CallbackTestPlugin.kt
platforms/apple/Sources/Nimbus/EncodableValue.swift
platforms/apple/Sources/Nimbus/JSContextConnection.swift
platforms/apple/Sources/Nimbus/WebViewConnection.swift
platforms/apple/Sources/NimbusTests/MochaTests.swift

* send the error when rejecting the promise
* iOS now correctly passes Error's to the promise rejection.
iOS rejection errors can now also be Encodable Error structures/classes.
* make the linter happy
* send interpolated error if unable to decode
* Ensure promises get rejected on android when an exception is thrown
Co-authored-by: Jason Foreman <jforeman@salesforce.com>

Promise rejection fix (#224)

---

packages/test-www/test/shared-tests.js
platforms/android/compiler-base/src/main/java/com/salesforce/nimbus/compiler/BinderGenerator.kt
platforms/android/compiler-v8/src/main/java/com/salesforce/nimbus/bridge/v8/compiler/V8BinderGenerator.kt
platforms/android/core/build.gradle
platforms/android/core/src/main/java/com/salesforce/nimbus/DefaultEventPublisher.kt
platforms/android/core/src/main/java/com/salesforce/nimbus/Event.kt
platforms/android/core/src/main/java/com/salesforce/nimbus/EventPublisher.kt
platforms/android/core/src/test/java/com/salesforce/nimbus/DefaultEventPublisherTest.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/plugin/ExpectPlugin.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/plugin/TestPlugin.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/v8/V8PluginTests.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/webview/WebViewPluginTests.kt
platforms/apple/Sources/NimbusTests/SharedTestsWebView.swift

This is the Android event publishing implementation matching the Plugin Event RFC. There is a new interface called `EventPublisher` which should be implemented by a `Plugin` that wants to support event publishing. The plugin can implement the methods in the interface, however most implementations will just want to delegate to the `DefaultEventPublisher` which handles managing listeners and publishing events. This is what that property delegation looks like:
```
class MyPlugin : Plugin, EventPublisher<MyEvent> by DefaultEventPublisher() {...}
```
There is an interface called `Event` which each concrete event class needs to implement. Also, the implementation of `Event` must be `@Serializable` which is enforced by the compiler.
Here is an example of defining a single event class:
```
class …
```

Android Event Publishing

---

packages/demo-www/src/components/app.ts
packages/demo-www/src/plugins/events.ts
packages/demo-www/src/plugins/log.ts
packages/demo-www/src/plugins/toast.ts
platforms/android/build.gradle
platforms/android/compiler-webview/src/main/java/com/salesforce/nimbus/bridge/webview/compiler/WebViewBinderGenerator.kt
platforms/android/core/src/main/java/com/salesforce/nimbus/Constants.kt
platforms/android/core/src/main/java/com/salesforce/nimbus/PrimitiveJSONEncodableExtensions.kt
platforms/android/demo-app/src/main/java/com/salesforce/nimbusdemoapp/MainActivity.kt
platforms/android/demo-app/src/main/res/layout/activity_main.xml
platforms/android/demo-app/src/main/res/values/strings.xml

This PR adds an example of how event publishing works to the demo app. There are two text fields, one which will publish the log plugin (and log to console), the other which will publish to the toast plugin. 
- Added event publishing to demo app
- Updated class discriminator for JSON serialization to be same as is with K2V8 serialization
- Updated k2v8 to 0.0.2
- Updated kotlin to 1.3.72

Added event publishing example to demo app

---

platforms/android/demo-app/src/main/java/com/salesforce/nimbusdemoapp/MainActivity.kt
platforms/android/modules/annotations/src/main/java/com/salesforce/nimbus/BoundMethod.kt
platforms/android/modules/annotations/src/main/java/com/salesforce/nimbus/BoundPlugin.kt
platforms/android/modules/compiler-base/src/main/java/com/salesforce/nimbus/compiler/BinderGenerator.kt
platforms/android/modules/compiler-base/src/main/java/com/salesforce/nimbus/compiler/CompilerExtensions.kt
platforms/android/modules/compiler-v8/src/main/java/com/salesforce/nimbus/bridge/v8/compiler/V8BinderGenerator.kt
platforms/android/modules/compiler-webview/src/main/java/com/salesforce/nimbus/bridge/webview/compiler/WebViewBinderGenerator.kt
platforms/android/modules/core-plugins/build.gradle.kts

This PR creates a new annotation `@BoundPlugin` which allows apps to annotate library plugins (`DeviceInfoPlugin`, for example) when they are used as fields or in value parameters which will trigger binder generation for them. Previously the binders were being generated in the library which would cause transitive dependencies to be included in the consuming app. 
The consumer can declare a plugin as a class variable, like this:
```
class SomeActivity : Activity {
@BoundPlugin 
val plugin: SomeLibraryPlugin = SomeLibraryPlugin()
}
```
This will generate whatever binders the library supports as long as the compiler for that binder is included in the consuming app. For example, if the plugin supports both webview and v8 but the app does not include the `compiler-v8` dependency then no v8 …

Generate core plugins in consuming app with new annotation

---

packages/test-www/test/shared-tests.js
platforms/apple/Sources/Nimbus/JSContextConnection.swift
platforms/apple/Sources/Nimbus/JSValueEncoder.swift
platforms/apple/Sources/NimbusTests/JSValueEncoderTests.swift
platforms/apple/Sources/NimbusTests/SharedTestsJSCore.swift
platforms/apple/Sources/NimbusTests/SharedTestsPlugin.swift
platforms/apple/Sources/NimbusTests/SharedTestsWebView.swift

Most of this was already implemented in `main` but I found a problem in `JSValueEncoder` that was causing the encoding of `EncodableValue` to encode no values. This fixes that, fixes the implementation in JSCore for the simple, non-structured enum, and adds tests to the shared test library for both cases.

Implementation of return value errors on iOS

---

.circleci/config.yml
platforms/android/build.gradle.kts
platforms/apple/Nimbus.xcodeproj/project.pbxproj

This adds two new tasks to the circle ci config, both only triggered by a tag push where the tag matches something that looks like `major.minor.patch-beta(beta number)`.
One for iOS which uploads a release to GitHub for the given tag, marked as pre-release.
One that calls a new Android gradle task that massages the project version to append `-SNAPSHOT` and cut out any beta strings and then calls the `artifactoryPublish` task to upload a snapshot.

CI for Pre-release builds

---

packages/nimbus-bridge/src/index.ts
packages/test-www/test/nimbus-core-tests.ts
packages/test-www/test/shared-tests.js
platforms/android/demo-app/src/main/java/com/salesforce/nimbusdemoapp/MainActivity.kt
platforms/android/modules/annotations/src/main/java/com/salesforce/nimbus/BoundMethod.kt
platforms/android/modules/bridge-v8/src/main/java/com/salesforce/nimbus/bridge/v8/V8Extensions.kt
platforms/android/modules/bridge-webview/src/main/java/com/salesforce/nimbus/bridge/webview/WebViewBridge.kt
platforms/android/modules/compiler-base/src/main/java/com/salesforce/nimbus/compiler/BinderGenerator.kt
platforms/android/modules/compiler-v8/src/main/java/com/salesforce/nimbus/bridge/v8/compiler/V8BinderGenerator.kt
platforms/android/modules/compiler-webview/src/main/java/com/salesforce/nimbus/bridge/webview/compiler/WebViewBinderGenerator.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/plugin/TestPlugin.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/v8/V8PluginTests.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/webview/WebViewMochaTests.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/webview/WebViewPluginTests.kt

This PR handles properly rejecting promises in Android with exceptions that occur on the native side, adding support for `@Serializable` exceptions. For normal non-declared exceptions the promise will be resolved with the `Exception.message`. A new property has been added to `@BoundMethod` called `throwsExceptions` which allows specifying one or more exceptions that the bound method can throw. If those exceptions are `@Serializable` the promise will be resolved with the serialized exception. 
Changes were necessary to the way synchronous returns are handled in the `WebView` binders in order to allow for handling/serializing the exception. `WebView` binders no longer will return a value and instead will invoke the `__nimbus.resolvePromise()` function with either the return value or the …

Android promise error handling

---

lerna.json
packages/nimbus-bridge/package-lock.json
platforms/android/build.gradle.kts
platforms/android/modules/annotations/build.gradle.kts
platforms/android/modules/bridge-v8/build.gradle.kts
platforms/android/modules/bridge-webview/build.gradle.kts
platforms/android/modules/compiler-base/build.gradle.kts
platforms/android/modules/compiler-v8/build.gradle.kts
platforms/android/modules/compiler-webview/build.gradle.kts
platforms/android/modules/core-plugins/build.gradle.kts
platforms/android/modules/core/build.gradle.kts
platforms/android/modules/nimbusjs/build.gradle.kts

Fixes a bug in the publishSnapshot task that didn't set the version at the correct time in the build lifecycle, so version was staying as x.x.x-beta instead of x.x.x-SNAPSHOT

fix(publish) - set snapshot version when publishing snapshot

---

platforms/android/modules/core/build.gradle.kts
platforms/android/modules/core/src/main/java/com/salesforce/nimbus/Constants.kt
platforms/android/modules/core/src/main/java/com/salesforce/nimbus/PrimitiveJSONEncodableExtensions.kt

This PR opts in to using `UnstableDefault` at the module level so that consumers aren't forced to do so. Since the `JsonConfiguration` is more of an implementation detail we shouldn't impose the opt in requirement on consumers.

Opt in to using UnstableDefault

---

platforms/android/modules/compiler-base/src/main/java/com/salesforce/nimbus/compiler/BinderGenerator.kt
platforms/android/modules/compiler-v8/src/main/java/com/salesforce/nimbus/bridge/v8/compiler/V8BinderGenerator.kt
platforms/android/modules/compiler-webview/src/main/java/com/salesforce/nimbus/bridge/webview/compiler/WebViewBinderGenerator.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/plugin/ExpectPlugin.kt

When generating a binder for an `internal` class, the nimbus compiler generates a 'public' extension method for creating the binder. This extension method takes an instance of the plugin class as an argument, which results in a compiler failure due to exposing an internal class in a public extension method. 
This fixes the issue and now the compiler generates the binder extension method with the same visibility as the plugin class it is extending.

fix: Generated binder extension methods now match visibility of the class being extended

---

packages/test-www/test/shared-tests.js
platforms/android/build.gradle.kts
platforms/android/modules/compiler-base/src/main/java/com/salesforce/nimbus/compiler/BinderGenerator.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/plugin/TestPlugin.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/v8/V8PluginTests.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/webview/WebViewPluginTests.kt

The plugin classes' metadata was not retrieved with getAnnotation call. Because of this, it was unable to determine the nullability of the fields.
This fixes the metadata and generates nullable fields on callbacks and other function calls.

Fix null Metadata for the kotlin classes.

---

platforms/apple/Sources/Nimbus/JSContextBridge.swift
platforms/apple/Sources/Nimbus/JSContextConnection.swift
platforms/apple/Sources/Nimbus/JSEvaluating.swift
platforms/apple/Sources/Nimbus/WebViewBridge.swift
platforms/apple/Sources/Nimbus/WebViewConnection.swift
platforms/apple/Sources/NimbusTests/CallJavascriptTests.swift

* Added overloaded `evaluate` method for web view bridge and JSContext bridge.
* Web view refactored to fix overloaded `evaluate`.

Enable native to call Javascript function without a return value.

---

packages/@nimbus-js/runtime/src/nimbus.js
packages/test-www/test/shared-tests.js
platforms/apple/Sources/Nimbus/WebViewConnection.swift
platforms/apple/Sources/NimbusTests/SharedTestsJSCore.swift
platforms/apple/Sources/NimbusTests/SharedTestsPlugin.swift
platforms/apple/Sources/NimbusTests/SharedTestsWebView.swift

Adding test cases for decoding error. When decoding fails, e.g. a string is passed when a number is expected, the promise in Javascript will be rejected and therefore can be handled in `catch(error => {...})`.
This PR does not unify `error` object passed to the handler in `catch` between web view and JSCore. Web view uses `DecodeError` which is our custom `Error` struct where as JSCore uses `DecodingError` that is out-of-the-box from Apple. Unification of error class is out of the scope for this work.
An edge case was discovered while working on this PR. Suppose there is a native function that is expecting a `String` parameter. Then from Javascript a simple simple Javascript object is passed instead, like `{aaa:`bbb`}`. Decoding of such parameter fails in JSCore, however, in web view, the …

Test cases for parameter decoding error.

---

package-lock.json
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/plugin/TestPlugin.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/v8/V8PluginTests.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/webview/WebViewPluginTests.kt

This adds the same tests for Android that were recently added for iOS to test invoking bound functions with parameters that should cause them to be rejected.
A number of scenarios were discovered that are currently not possible to support on Android without further work. These scenarios are currently commented out and I will create a story for the backlog to come up with a solution for both Android and iOS that can be implemented in a future version.

Android parameter rejection tests

---

platforms/apple/Sources/Nimbus/JSValueDecoder.swift
platforms/apple/Sources/Nimbus/JSValueEncoder.swift

These methods can be extremely beneficial to LMR Context that is a wrapper object containing JSCore.

Make JSValue encoder and decoder public.

---

.circleci/config.yml

Use an older version of github-release-cli to try to fix publishing issue.

Roll back to using github-release-cli at 1.3.1

---

.circleci/config.yml

I think having these two tasks named the same was causing only the last one in the file to get parsed and therefore only working on pre-releases. This should fix that.

Fix circle jobs that had identical names

---

platforms/android/gradle.properties

Bintray has updated the original bintray package (https://bintray.com/salesforce-mobile/android/nimbus) to publish to jcenter, so this change to package name is not longer necessary.  Future publications to the package 'nimbus' should also publish to jcenter.

reverting package name with bintray fix

---

packages/@nimbus-js/runtime/src/nimbus.js
packages/test-www/test/shared-tests.js
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/plugin/TestPlugin.kt
platforms/android/shared-tests/src/androidTest/java/com/salesforce/nimbus/bridge/tests/webview/WebViewPluginTests.kt
platforms/apple/Sources/NimbusTests/SharedTestsPlugin.swift
platforms/apple/Sources/NimbusTests/SharedTestsWebView.swift

With this change, Uint8Array values will be transformed into
base64-encoded strings as they cross to native. This should be better
than letting them fall to `JSON.stringify` which turns them into a
`map<string, int>`.
Support for headless environments is not yet implemented.

Add support for Uint8Array values from web view
